server:
  port: 8085
eureka:
 client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: api-gateway
 cloud:
    gateway:
      routes:
      - id: passeger
        uri: http://localhost:8000/
        predicates:
        - Path=/passenger/**
      - id: flight
        uri: http://localhost:8001/
        predicates:
        - Path=/flight/**
      - id: booking
        uri: http://localhost:8002/
        predicates:
        - Path=/booking/**
      - id: fare
        uri: http://localhost:8003/
        predicates:
        - Path=/fare/**
      - id: checkin
        uri: http://localhost:8004/
        predicates:
        - Path=/checkin/**  
          
        